### ISSUE TITLE
  ToDo / Notes button not working  and  UI  is very simple  

### ISSUE THREAD

**Issue by DheerajRay-01** [ClubToCode/Notzy#4]
1. when we click on  ToDo And Notes button  , it is not go to Todo or Notes page .

2. User interface  is very simple .

![Capture1](https://github.com/ClubToCode/Notzy/assets/144889143/43d42075-1aee-4529-bc8b-43acf6d896b8)

**Comment by Ronit-gurjar** [comment]
the PR you created for this issue is merged & closed so I am closing this issue.
