### ISSUE TITLE
Notes section not created

### ISSUE THREAD

**Issue by VinayakNPN** [ClubToCode/Notzy#6]
**Describe the bug**
The "Notes" button (anchor tag) is not functionable , It's not directing me to any page 

**Expected behavior**
Expected behavior  would be that when a user clicks on the "Notes" section, a text box or another area appears where the user can input notes. These notes would likely be saved and would be retrievable later.

**Screenshots**
![image](https://github.com/ClubToCode/Notzy/assets/144888538/0f97ebcf-9a01-4a62-bdd2-4b5885f32a9d)
![image](https://github.com/ClubToCode/Notzy/assets/144888538/8791cad2-e1d0-48d9-8424-9f69f2dbb31d)

**Comment by Ronit-gurjar** [comment]
Okay! Would you like to work on this issue?

**Comment by VinayakNPN** [comment]
> Okay! Would you like to work on this issue?

Sure I can fix this issue 👍🏻

**Comment by Ronit-gurjar** [comment]
hey @VinayakNPN ... looks like ritik has started working on this issue...do you mind if i provide you a different task?

**Comment by VinayakNPN** [comment]
> hey @VinayakNPN ... looks like ritik has started working on this issue...do you mind if i provide you a different task? 

Oh ok No problem in that let him work on this issue 😌👍🏻

**Comment by Ronit-gurjar** [comment]
if you want to work on anything else please create a new issue for it. i am closing this one.

### happy coding 🫡🔥
